#!/usr/bin/env python3
"""Generate the Class B compaction table (LaTeX) from benchmark JSONs.

Prefers the structured harness files (results/gc_benchmark_classB_*.json,
written by run_gc_bench.py); falls back to the legacy aggregated
gc-bench/results/gc_results.json for benchmarks not yet re-collected.
"""
import glob
import json
import os
import statistics as st
import sys
from collections import defaultdict

RES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "results")
LEGACY = "/mydata/gc-bench/results/gc_results.json"

ROWS = [("h2", "768M", 5), ("pmd", "336M", 3),
        ("xalan", "80M", 3), ("lusearch", "128M", 3)]
CONFIGS = [("None", "STW"), ("Uffd", r"\uffd"), ("R1", r"\name")]


def collect():
    """(bench, config) -> {"time_s": [..], "pause_ms": [..]}"""
    out = defaultdict(lambda: {"time_s": [], "pause_ms": []})
    hs = defaultdict(lambda: {"time_s": [], "pause_ms": []})
    for f in sorted(glob.glob(os.path.join(RES, "gc_benchmark_classB_*.json"))):
        for r in json.load(open(f)):
            key = (r["bench"], r["config"])
            res = r["results"]
            if not res.get("passed"):
                continue
            if r["kind"] == "throughput" and res.get("last_iter_ms"):
                hs[key]["time_s"].append(res["last_iter_ms"] / 1000)
            if r["kind"] == "pauses" and res.get("pause_avg_us"):
                hs[key]["pause_ms"].append(res["pause_avg_us"] / 1000)
    # Only prefer harness data for a benchmark once every config has both
    # record kinds -- otherwise an in-flight rerun would produce partial
    # rows mixing configurations.
    complete = {b for b, _, _ in ROWS
                if all(hs[(b, c)]["time_s"] and hs[(b, c)]["pause_ms"]
                       for c, _ in CONFIGS)}
    seen_hs = set()
    for (b, c), d in hs.items():
        if b in complete:
            out[(b, c)] = d
            seen_hs.add((b, c))
    if os.path.exists(LEGACY):
        heaps = {b: h for b, h, _ in ROWS}
        for r in json.load(open(LEGACY)):
            if r["class"] != "B":
                continue
            key = (r["bench"], r["config"])
            if key in seen_hs:            # harness data wins
                continue
            if r.get("heap_mib") != int(heaps.get(r["bench"], "0M")[:-1]):
                continue
            res = r["results"]
            if not res.get("passed"):
                continue
            if r["kind"] == "throughput" and res.get("last_iter_ms"):
                out[key]["time_s"].append(res["last_iter_ms"] / 1000)
            if r["kind"] == "pauses" and res.get("pause_avg_us"):
                out[key]["pause_ms"].append(res["pause_avg_us"] / 1000)
    return out


def fmt(vals, unit):
    if not vals:
        return "--"
    m = st.mean(vals)
    return f"{m:.1f}s" if unit == "s" else f"{m:.0f}ms"


def main():
    data = collect()
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(RES, "gc_table.tex")
    lines = [
        r"% Generated by print_gc_table.py -- do not edit by hand.",
        r"\begin{table}[!t]", r"\centering", r"\small",
        r"\begin{tabular}{l rr rr rr}", r"\toprule",
        r" & \multicolumn{2}{c}{STW} & \multicolumn{2}{c}{\uffd} & \multicolumn{2}{c}{\name} \\",
        r"\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}",
        r"Benchmark & time & pause & time & pause & time & pause \\",
        r"\midrule",
    ]
    for bench, heap, _ in ROWS:
        cells = []
        for cfg, _ in CONFIGS:
            d = data[(bench, cfg)]
            cells.append(fmt(d["time_s"], "s"))
            cells.append(fmt(d["pause_ms"], "ms"))
        lines.append(rf"{bench} ({heap}) & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}",
              r"\caption{Concurrent compaction on DaCapo: iteration time and mean GC pause.}",
              r"\label{tab:gc-compaction}", r"\end{table}"]
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(out)
    for bench, heap, _ in ROWS:
        for cfg, _ in CONFIGS:
            d = data[(bench, cfg)]
            n = len(d["time_s"])
            print(f"  {bench} {cfg}: n={n} "
                  f"time={st.mean(d['time_s']):.2f}s pause={st.mean(d['pause_ms']):.0f}ms"
                  if n else f"  {bench} {cfg}: NO DATA", file=sys.stderr)


if __name__ == "__main__":
    main()
